### ISSUE TITLE
go get -u fails - recompile with -fPIC

### ISSUE THREAD

**Issue by mzimmerman** [gen2brain/go-fitz#1]
I would like to use this library, however go get -u is failing and I'm unsure how to fix it.  I'm experienced with Go, yet I haven't done much with shared libraries and cgo.  A sample of errors is below.  I assume I just need to recompile them with the flag as suggested, however, I'm not sure where they came from.

> /usr/bin/ld: /src/github.com/gen2brain/go-fitz/libs/libmupdfthird_linux_amd64.a(tgt.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: /src/github.com/gen2brain/go-fitz/libs/libmupdfthird_linux_amd64.a(inffast.o): relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: /src/github.com/gen2brain/go-fitz/libs/libmupdfthird_linux_amd64.a(cmsalpha.o): relocation R_X86_64_32S against `.rodata.FormattersAlpha.7892' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: /src/github.com/gen2brain/go-fitz/libs/libmupdfthird_linux_amd64.a(cmscnvrt.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: /src/github.com/gen2brain/go-fitz/libs/libmupdfthird_linux_amd64.a(cmsgamma.o): relocation R_X86_64_32 against `.data.DefaultCurves' can not be used when making a shared object; recompile with -fPIC

**Comment by gen2brain** [comment]
Hello, add `-tags gcc7` to go get command. I should add that to README.

**Comment by mzimmerman** [comment]
Well that was easy, thanks!
