### ISSUE TITLE
fitz is not importing correctly

### ISSUE THREAD

**Issue by Axibord** [gen2brain/go-fitz#104]
![image](https://github.com/gen2brain/go-fitz/assets/46763664/0e43d6b3-0911-4c08-9741-135488cc3964)

The import seem to be broken, i have no idea why, i tried with different environments.

I'm on Windows 11 and not using WSL

**Comment by gen2brain** [comment]
You are either missing a C compiler or trying to compile with CGO_ENABLED=0.

**Comment by Axibord** [comment]
> You are either missing a C compiler or trying to compile with CGO_ENABLED=0.

Thanks, it worked, you were right! Even the autocomplete was not working, I'm new to Golang that's why I guess.
