### ISSUE TITLE
Error when convert PDF to Image

### ISSUE THREAD

**Issue by guoquanle** [gen2brain/go-fitz#107]
[cleancode.pdf](https://github.com/user-attachments/files/15606236/cleancode.pdf)
when using doc.Image(pageNumber),this PDF will error, error page is 211.

error info:
warning: jbig2dec error: DW value (-75) would make SYMWIDTH (0) negative at symbol 655 (segment 0)
warning: jbig2dec warning: failed to decode; treating as end of file (segment 0)
error: aborting process from uncaught error!

**Comment by guoquanle** [comment]
[Uploading cleancode.pdf…]()
this pdf

**Comment by guoquanle** [comment]
[cleancode.pdf](https://github.com/user-attachments/files/15606064/cleancode.pdf)

**Comment by gen2brain** [comment]
Try with an external library, the bundled library is compiled without CJK.

**Comment by guoquanle** [comment]
Any external library can be recommend? 
And I encountered a situation where there was no CJK before, and it gave such an error instead of a direct crash. 
error: cannot find builtin CJK font

**Comment by gen2brain** [comment]
You need MuPDF library installed, then use `extlib` tag, and if needed add `static` or `pkgconfig` tags.

**Comment by gen2brain** [comment]
Now it will return error for broken files when load/run page is started.
