### ISSUE TITLE
Out of Memory issues with frequent requests 

### ISSUE THREAD

**Issue by conor-nsurely** [gen2brain/go-fitz#108]
Hello,

I know there is already a [related issue](https://github.com/gen2brain/go-fitz/issues/9) , but it is from 5 years ago so perhaps something has changed.

`	text := ""

	doc, err := fitz.New(file)
	if err != nil {
		return err
	}
	defer doc.Close()

	// Extract pages as images and extract text
	for n := 0; n < doc.NumPage(); n++ {
		img, err := doc.Image(n)
		if err != nil {
			return err
		}
	`
Memory usage grows for each request(or pdf page I suppose) which isn't an issue, however it doesn't seem to release quickly enough leading to crashes when requests are frequent. Is there a way to force it to release resources? Is there anything else I need to add or should 'doc.Close()' handle all cleanup? I've tried removing everything except the above code block and it still occurs, so I don't think it's a different part of the application causing it.

This is leading to frequent crashing due to running out of memory even in a container with 8GiB allocated.

Otherwise the library is working great :) 

Thanks

**Comment by gen2brain** [comment]
Close() should close and drop the document, context, and stream, i.e. it should clean all the memory. How large are PDFs? I am guessing that it is related to the context created with `FZ_STORE_UNLIMITED` hard-coded. You didn't show all your code, but it looks like you are doing more things, extracting text, etc. I know for example ImageMagick can use a LOT of memory when dealing with PDF and can be controlled with the `-limit` option, but here it is hard-coded.

You can try to change that to `FZ_STORE_DEFAULT` (256 << 20), or just set some value. I should probably allow optional parameters and fallback to the default value, unlimited is not a good idea.

**Comment by conor-nsurely** [comment]
@gen2brain 
Hey,
Thanks for getting back to me.

The pdfs are about 2-3 MiB on average, largest being 7-8MiB.
The pdf pages are converted to images and then sent to the Google vision api to perform OCR.

`FZ_STORE_DEFAULT` where would I set this?
Once that is set will it clean up the old memory once it reaches the limit or what happens

**Comment by gen2brain** [comment]
I have added the `MaxStore` global variable, so you can set the size you need, default is `256 << 20`. 
You can check the header files for docs, i.e. https://github.com/gen2brain/go-fitz/blob/master/include/mupdf/fitz/context.h#L306.

**Comment by conor-nsurely** [comment]
Hey @gen2brain thanks for fixing this so quickly.

Do you know when this might be released?

**Comment by gen2brain** [comment]
When the new mupdf libraries are built, probably will not happen during summer, just use @latest for now.

**Comment by conor-nsurely** [comment]
Okay will do.

Thanks

**Comment by 1174823821** [comment]
Hi @conor-nsurely 

I noticed that this issue (#108) has been closed, but I'm not quite sure how the problem was resolved in the code. Could you please provide a detailed code example or explain the solution?

**Comment by lingoo** [comment]
my test code:
```go
func main() {
	// Extract pages as images
	for n := 0; n < 1000; n++ {
		test(n)
	}

	http.ListenAndServe(":8080", nil)
}

func test(n int) {
	doc, err := fitz.New("test.pdf")
	if err != nil {
		panic(err)
	}

	defer doc.Close()
	log.Println("Extracting page", n)
	_, err = doc.ImagePNG(0, 300)
	if err != nil {
		panic(err)
	}
}
```
`test` function just similar to my api and I use `fitz.NewFromMemory(*bytes)` to replace `fitz.New`. memory never be free for long time. how to fix it. thx.

**Comment by conor-nsurely** [comment]
@asish-tom Are you seeing a linear increase in memory usage for each page/document processed? 

I thought this issue was resolved, but we are experiencing crashes again in our containers and I think it might be stemming from this library 🤔

**Comment by gen2brain** [comment]
This could be related to this line https://github.com/gen2brain/go-fitz/blob/master/fitz.go#L236, when commented out it crashes, but it is ok for ImagePNG, there is something about this here https://github.com/gen2brain/go-fitz/pull/103. When I first checked this I didn't find a reason for crash and never did find time to get back to this, maybe someone has some idea. You can try with ImagePNG instead to see if there is any difference, that would confirm where the bug is.

**Comment by gen2brain** [comment]
Ok, pixmap is dropped in https://github.com/gen2brain/go-fitz/commit/d6df0822d756189b4bc827e84a01d913c37ab924. Please try with the latest master.

**Comment by gen2brain** [comment]
And also, libraries are updated to latest release.

**Comment by gen2brain** [comment]
Thanks, I pushed a fix and tagged a new release. I did try to replicate this with the HTTP server but I was using the file.
