### ISSUE TITLE
Vendoring the include files

### ISSUE THREAD

**Issue by agentabstract** [gen2brain/go-fitz#111]
I see there was a lot of people asking about vendoring of the include files.  I was able to fix this in my abandoned fork by adding a go file to each included directory and sub directory.  

```
// +build required

// Package dummy prevents go tooling from stripping the c dependencies.
package dummy

```
The package name is meaningless, you just need the build required part at the top, and a package name.

**Comment by gen2brain** [comment]
Thanks, I don't care about the vendor but if that can stop new related issues I am interested. PR is welcome, I don't have the time for that.

**Comment by agentabstract** [comment]
Heard.  I'll do that when I get a moment myself.

**Comment by gen2brain** [comment]
Support for vendoring is added.
