### ISSUE TITLE
feat: support windows/arm64

### ISSUE THREAD

**Issue by iwilltry42** [gen2brain/go-fitz#112]
According to `fitz_cgo.go` and the libs files, Windows arm64 (aarch64) doesn't seem to be supported directly.
Is there any time and interest for adding it?

**Comment by gen2brain** [comment]
If it is easy for me to add new crossdev toolchain on mu system I will add it. Not sure, I don't even know what devices use windows/arm64. I will check after the summer is over.

**Comment by iwilltry42** [comment]
I used https://github.com/mstorsjo/llvm-mingw but still failed building the mupdf lib because of sse4.1 instructions. I must be missing something, but I'm also not an expert in this field.

**Comment by gen2brain** [comment]
Ok, I added libraries for windows/arm64.

```
# CGO_ENABLED=1 CC=aarch64-w64-mingw32-gcc GOOS=windows GOARCH=arm64 go build -ldflags '-s -w'

# file example.exe
example.exe: PE32+ executable (console) Aarch64, for MS Windows, 7 sections
```
