### ISSUE TITLE
Getting error when building

### ISSUE THREAD

**Issue by abhijitpratinidhi** [gen2brain/go-fitz#113]
Hi,

I am using the fitz library to convert pdf into png.While building i am getting the below error - .CGO_LDFLAGS is set to '-lmupdf -lm -lmupdf-third -lfreetype -ljbig2dec -lharfbuzz -ljpeg -lopenjp2 -lz' and CGO_CFLAGS to '-O2 -g' .

go build -v -o ./cmd/pdfconv/pdfconv ./cmd/pdfconv/
github.com/gen2brain/go-fitz
# github.com/gen2brain/go-fitz
vendor/github.com/gen2brain/go-fitz/fitz.go:6:10: fatal error: 'mupdf/fitz.h' file not found
#include <mupdf/fitz.h>
         ^~~~~~~~~~~~~~

**Comment by gen2brain** [comment]
You are using vendor, see https://github.com/gen2brain/go-fitz/issues/111 and many other related issues. Also, not sure why you are using CFLAGS/LDFLAGS.

**Comment by abhijitpratinidhi** [comment]
What should be the fix for vendor/github.com/gen2brain/go-fitz/fitz.go:6:10: fatal error: 'mupdf/fitz.h' file not found ?

**Comment by gen2brain** [comment]
As I wrote, see https://github.com/gen2brain/go-fitz/issues/111, or do not use vendor.

**Comment by abhijitpratinidhi** [comment]
Thanks @gen2brain it worked without vendor.Any idea how can i use this library in dockerfile ,its giving the same error with a static-debian12 image .

**Comment by gen2brain** [comment]
No idea, why should anything be different? What is that static-debian anyway, you will not get static binary, it will link to libc, unless you also build with --static.

**Comment by gen2brain** [comment]
Support for vendoring include files and libs is added.
