### ISSUE TITLE
 garbled code when convert pdf to txt

### ISSUE THREAD

**Issue by FunkyYang** [gen2brain/go-fitz#115]
```

func convertPDFToMD(pdfPath, mdPath string) error {
	doc, err := fitz.New(pdfPath)
	if err != nil {
		return err
	}
	defer doc.Close()

	numPages := doc.NumPage()
	var mdContent string

	for i := 0; i < numPages; i++ {
		text, err := doc.Text(i)
		if err != nil {
			return err
		}

		mdContent += text + "\n"
	}

	err = os.WriteFile(mdPath, []byte(mdContent), 0644)
	if err != nil {
		return err
	}

	return nil
}
```
when convert pdf to text sometimes will be garbled code in text ?why

**Comment by FunkyYang** [comment]
I want you act as a proofreader. I will provide you texts and I would like you to review them 

for any spelling, grammar, or punctuation errors. Once you have finished reviewing the 

text, provide me with any necessary corrections or suggestions for improve the text. 

我要你充当校对员。我将为您提供⽂本，并希望您检查它们是否有任何拼写，语法或标点符号错

误。完成⽂本审阅后，请向我提供任何必要的更正或改进⽂本的建议。

**Comment by FunkyYang** [comment]
the problem pdf 
[Uploading 《指令词合集》中英双语版.pdf…]()

**Comment by gen2brain** [comment]
If you need CJK fonts you must build with the external library. The bundled ones are purposely built without CJK.

**Comment by FunkyYang** [comment]
build mupdf with CJK? What can I do next

**Comment by gen2brain** [comment]
Build tags are described in README, you need `extlib` and perhaps `static` or `pkgconfig` depending on how you install/compile mupdf.
