### ISSUE TITLE
No package 'mupdf' found

### ISSUE THREAD

**Issue by yanglikkk** [gen2brain/go-fitz#116]
![image](https://github.com/user-attachments/assets/51dbbadb-0fa1-44d7-b9db-bf2fea5832ed)

**Comment by gen2brain** [comment]
How is this issue from the screenshot related to this repo? Sorry, but I don't have the time for this. Does the MuPDF source include `.pc` file for pkg-config or are only specific distros adding it? Why not create one yourself? I cannot provide support for user issues with compiling. Also, if you are not using pkg-config why do you insist on using it? Just use `extlib` and maybe `static` build tag if you compiled statically.
