### ISSUE TITLE
NewFromReader/NewFromMemory will panic when an empty reader/byte[] is passed.

### ISSUE THREAD

**Issue by kvii** [gen2brain/go-fitz#126]
minimal reproduce:

```go
var r bytes.Reader      // r.Read will return EOF
fitz.NewFromReader(&r)  // panic: runtime error: index out of range [0] with length 0
```

This line will panic when b is an empty slice.
https://github.com/gen2brain/go-fitz/blob/a89943702a67236bef7d80eecbf90fd5743a6655/fitz_cgo.go#L138

**Comment by gen2brain** [comment]
Sure, it is expected to panic when you pass an empty or nil slice. The solution is to avoid passing nil and empty slices. If you are bothered by this, you can send PR. I see this as minor importance so that I would work on it.

**Comment by kvii** [comment]
#127 So I add a check. But I don't know how to run test in a non-cgo environment. If you think it's unnecessary, just close it.

**Comment by gen2brain** [comment]
Thanks. For non-cgo, you need `libffi.so and libmupdf.so`, or in Windows, that is `.dll`; just put them together with your `.exe` in the same directory and compile with `-tags nocgo` or with `CGO_ENABLED=0`; if dlls depend on something else, you also need to copy all dependencies.
