### ISSUE TITLE
I got extra \n when i extract text from epub/mobi

### ISSUE THREAD

**Issue by helios741** [gen2brain/go-fitz#129]
Hello, my epub file is the follow image:
![image](https://github.com/user-attachments/assets/a8d991e6-2193-4a35-8700-ffdda7538941)

when i use go-fitz to extract text i got extract \n as follow:
![image](https://github.com/user-attachments/assets/6433e131-ae01-47b9-b40f-a94f7fd75f57)

i don't need extra black lines, how can i handle it please.

**Comment by helios741** [comment]
plus，Some paragraphs are continuous, but the result may have \n.
This is e-book format:
![image](https://github.com/user-attachments/assets/19379915-9490-498d-be49-cc01304881f3)

but i got:
![image](https://github.com/user-attachments/assets/6412d611-5ef8-42c4-b019-6883ff0aab80)

**Comment by gen2brain** [comment]
Are you aware this is just a wrapper for MuPDF? I don't know what answer you expect here; that is how it works, and it cannot be changed in this repo.
