### ISSUE TITLE
Modify the image size

### ISSUE THREAD

**Issue by bipin-mi** [gen2brain/go-fitz#15]
Converting the 4x6 inch size pdf to jpg image using the code as given on readme file for *pdf as image*. The image is generated easily but its size is 1200 x 1800 pixel. Didn't find any options for size related things. Can you please help with this.

**Comment by gen2brain** [comment]
You can use ImageDPI() to set DPI for image, with just Image() default is 300.

**Comment by bipin-mi** [comment]
> You can use ImageDPI() to set DPI for image, with just Image() default is 300.

Done. It works. Thanks
