### ISSUE TITLE
go get -u fails with extlib

### ISSUE THREAD

**Issue by ccmcpp** [gen2brain/go-fitz#17]
Can you change file fitz_cgo_extlib.go:
#cgo LDFLAGS: -lmupdf
to 
#cgo LDFLAGS: -lmupdf -lm -lmupdfthird

It will run error without mupdfthird.
Thank you very much.

**Comment by gen2brain** [comment]
I added `static` tag in https://github.com/gen2brain/go-fitz/commit/62357ab3d4a9b05d7709db2684696aca23005054 . Try to build with `-tags 'extlib static'` . I cannot just add `-lmupdfthird`, shared library doesn't use that.

**Comment by ccmcpp** [comment]
So fast!!! Thank you very mush.
