### ISSUE TITLE
error: no builtin cmap file: Adobe-GB1-UCS2

### ISSUE THREAD

**Issue by HappyFerry** [gen2brain/go-fitz#18]
hello
when pdf convert to jpg，console report:
```
error: no builtin cmap file: Adobe-GB1-UCS2
warning: unrecoverable error; ignoring rest of page
```
whether the the encodings character is missing ?
can i set default encoding when lack to support like  `Adobe-GB1-UCS2` or others ?
or how can fix it

**Comment by HappyFerry** [comment]
just need to compile mupdf new version lib, the problem fixed.

**Comment by esprajwol** [comment]
@HappyFerry, can you please make a workflow solution, having same issue on mine as well

**Comment by HappyFerry** [comment]
> @HappyFerry, can you please make a workflow solution, having same issue on mine as well

pull latest version,  and compile to run in local environment,  it is ok

**Comment by gen2brain** [comment]
This should be fixed now with the new release. If you still have issues you can always just use `extlib`.

**Comment by zobx** [comment]
error: no builtin cmap file: UniGB-UCS2-H
warning: unrecoverable error; ignoring rest of page

 how can fix it?
