### ISSUE TITLE
how to go build in mac or window ?

### ISSUE THREAD

**Issue by shumintao** [gen2brain/go-fitz#19]

**Comment by HappyFerry** [comment]
just turn your view to mupdf project








在 2020-01-05 18:59:40，"清晨的粥" <notifications@github.com> 写道：

**Comment by sawyer523** [comment]
Mac
1. brew install mingw-w64
2. env GOOS="windows" GOARCH="amd64" CGO_ENABLED="1" CC="x86_64-w64-mingw32-gcc" go build

**Comment by SmallRoomLabs** [comment]
That works absolutely fine for Linux as well.  I did an `apt-get install mingw-w64` in my Ubuntu-based devcontainer and could create a working windows exe without any issues using that"'go build" -incantation
