### ISSUE TITLE
error: no builtin cmap file: UniGB-UCS2-H

### ISSUE THREAD

**Issue by Vericlongmore** [gen2brain/go-fitz#24]
error: no builtin cmap file: UniGB-UCS2-H
warning: unrecoverable error; ignoring rest of page
err 0
error: no builtin cmap file: UniGB-UCS2-H
warning: unrecoverable error; ignoring rest of page
error: no builtin cmap file: UniGB-UCS2-H
warning: unrecoverable error; ignoring rest of page

**Comment by Vericlongmore** [comment]
Pdf to picture

**Comment by gen2brain** [comment]
This should be fixed now.
