### ISSUE TITLE
there is something unexpected when compiling my app

### ISSUE THREAD

**Issue by Nothing-no** [gen2brain/go-fitz#28]
when i build my app, it always told me the following error:
![image](https://user-images.githubusercontent.com/55579792/119608016-d9158400-be27-11eb-8e94-fd512a57c8bc.png)

**Comment by gen2brain** [comment]
You are using a very old GCC compiler. Just compile with version >= 7, the resulting binary will work on old systems. There used to be a build tag `nopie` just for that but I dropped support for such old compilers.

**Comment by Nothing-no** [comment]
> You are using a very old GCC compiler. Just compile with version >= 7, the resulting binary will work on old systems. There used to be a build tag `nopie` just for that but I dropped support for such old compilers.
but my gcc version is 7.5.0
![image](https://user-images.githubusercontent.com/55579792/119611526-61e2ee80-be2d-11eb-8765-9fe3980fd394.png)

**Comment by gen2brain** [comment]
Then I was wrong about the correct version, any way the solution is the same, what is that, Ubuntu 16?

**Comment by Nothing-no** [comment]
> Then I was wrong about the correct version, any way the solution is the same, what is that, Ubuntu 16?

no, i am using Ubuntu 20.04 LTS

**Comment by gen2brain** [comment]
Can you check this for me?

`gcc -v |& grep -o -e '[^ ]*pie'`

**Comment by Nothing-no** [comment]
> Can you check this for me?
> 
> `gcc -v |& grep -o -e '[^ ]*pie'`

my pleasure
![image](https://user-images.githubusercontent.com/55579792/119623234-8db8a100-be3a-11eb-9a12-74da6bad7fce.png)

**Comment by gen2brain** [comment]
I just noticed that you do not use the latest version but some from 2020, please try with the latest version.

**Comment by Nothing-no** [comment]
> I just noticed that you do not use the latest version but some from 2020, please try with the latest version.

em~~, isn't v1.18.0 the latest version?

**Comment by gen2brain** [comment]
From your screenshot (can you just paste text) you are using 20201207 version.

**Comment by gen2brain** [comment]
Well, I just installed Ubuntu 20.04, installed build-essential, golang and git, and everything works properly. I tried to build with and without Go modules. Gcc version is 9.3.0 actually and is built with --enable-default-pie. So, not sure what you are doing exactly, what is your dev env and why so many differences.

**Comment by Nothing-no** [comment]
> Well, I just installed Ubuntu 20.04, installed build-essential, golang and git, and everything works properly. I tried to build with and without Go modules. Gcc version is 9.3.0 actually and is built with --enable-default-pie. So, not sure what you are doing exactly, what is your dev env and why so many differences.

it confused me if i didn't use go-micro frame in my program, there is no such problem
