### ISSUE TITLE
my service crash in new verion go-fitz

### ISSUE THREAD

**Issue by TimRazumov** [gen2brain/go-fitz#29]
after upgrading to version v1.18.0 my programm crash with intarnal go-fitz error:
```
warning: cannot load object (19 0 R) into cache
error: aborting process from uncaught error!
```
in version v0.0.0-20210316172528-f0a07eb93909 his was not

**Comment by gen2brain** [comment]
Does that happen with all documents or you have only some that are problematic? In bindings, errors are not "caught", if that is something internal to mupdf I cannot help.

**Comment by TimRazumov** [comment]
https://github.com/ArtifexSoftware/mupdf/blob/master/source/pdf/pdf-xref.c#L2280
https://github.com/ArtifexSoftware/mupdf/blob/master/source/fitz/error.c#L153

**Comment by TimRazumov** [comment]
in doc mupdf. it seems your wrapper doesn't have this processing. 
will it be difficult for you to add this?

![image](https://user-images.githubusercontent.com/56147892/120097941-da062880-c13b-11eb-9d64-05ecd3b4385c.png)

**Comment by TimRazumov** [comment]
Hello. have any ideas how you can fix this?

**Comment by gen2brain** [comment]
I was not able to reproduce with files I usually use for testing. I don't have time to mess with this currently, also, if you or someone else can fix this, I accept PRs.

**Comment by diegobernardes** [comment]
I think the only way of solving this problem is using Go as a simple glue layer instead of directly interacting with the library. I don't think it's possible at all to use MuPDF try/catch mechanism directly with Go. 

I've been working on a wrapper of MuPDF with Go that is very specific for the company that I'm working for, but it may give some ideas: https://github.com/nitro/lazypdf

**Comment by TimRazumov** [comment]
hello @diegobernardes. I saw your library, but it's not entirely clear to me how to install it, which I described in this issue: https://github.com/Nitro/lazypdf/issues/51

**Comment by gen2brain** [comment]
Closing this in favor of https://github.com/gen2brain/go-fitz/issues/57.

**Comment by gen2brain** [comment]
This should be fixed in https://github.com/gen2brain/go-fitz/commit/f15918d712b55047e829b1fe6ce0b46651ca0e40.
