### ISSUE TITLE
Provide ImageAsPNG method example

### ISSUE THREAD

**Issue by raliste** [gen2brain/go-fitz#3]
The Go image/png encoder is quite slow. Would you be able to provide an example with mupdf native png writer?

**Comment by gen2brain** [comment]
I tried to add ImageAsPNG method, but for now it doesn't work. Not sure if I use it properly or is it related to  some (now closed) bugs in which case I will need to compile and update lib for all arches.

**Comment by gen2brain** [comment]
Added in https://github.com/gen2brain/go-fitz/commit/142cf5d030bab587074caa9002462d64851e915a .
