### ISSUE TITLE
undefined reference to `__imp__ftelli64'

### ISSUE THREAD

**Issue by hajsf** [gen2brain/go-fitz#32]
Trying to test it at Windows, but got:
```bash
# github.com/gen2brain/go-fitz
C:/Users/hasan/Documents/GoWorkPlace/pkg/mod/github.com/gen2brain/go-fitz@v1.18.0/libs/libmupdf_windows_amd64.a(output.o):output.c:(.text$file_tell+0xe): undefined reference to `__imp__ftelli64'
C:/Users/hasan/Documents/GoWorkPlace/pkg/mod/github.com/gen2brain/go-fitz@v1.18.0/libs/libmupdf_windows_amd64.a(output.o):output.c:(.text$file_seek+0x14): undefined reference to `__imp__fseeki64'
C:/Users/hasan/Documents/GoWorkPlace/pkg/mod/github.com/gen2brain/go-fitz@v1.18.0/libs/libmupdf_windows_amd64.a(stream-open.o):stream-open.c:(.text$seek_file+0x1d): undefined reference to `__imp__fseeki64'
C:/Users/hasan/Documents/GoWorkPlace/pkg/mod/github.com/gen2brain/go-fitz@v1.18.0/libs/libmupdf_windows_amd64.a(stream-open.o):stream-open.c:(.text$seek_file+0x2e): undefined reference to `__imp__ftelli64'
collect2.exe: error: ld returned 1 exit status
```

**Comment by gen2brain** [comment]
What compiler are you using? The MinGW-w64 should have fteli64, also recent MinGW from mingw.org.

**Comment by hajsf** [comment]
mmm, May I did not understand the installation, just having Go1.16.6 and run `go get ...` command!
Do I need to do some other things?

**Comment by gen2brain** [comment]
See https://golang.org/cmd/cgo/ and e.g https://dave.cheney.net/2016/01/18/cgo-is-not-go.

**Comment by hajsf** [comment]
Trying to understanding, this is something completely new for me, if you can add some more explanation in the  required installation/build, it will be great help. thanks

**Comment by gen2brain** [comment]
The instructions are the same for every project that uses C libraries, you need a C compiler installed, like Mingw-w64 or TDM-GCC.

**Comment by gen2brain** [comment]
When I tested other projects in Windows, the easiest for me was to install TDM-GCC, of course in Linux everything is much simpler to install/configure.

**Comment by hajsf** [comment]
Thanks a lot, I installed [tdm-gcc](https://jmeubank.github.io/tdm-gcc/download/)  and things are great now, I would recommend you add small note about this in the installation section, I expect not to be the only who do not this :)
