### ISSUE TITLE
Updating pdf file

### ISSUE THREAD

**Issue by hajsf** [gen2brain/go-fitz#34]
hi, In my app, i'm reading list of 'pdf' files, and list those having specific words.

Is there a way to modify the file itself, let's say I want to see if the file contains the word 'fitz', and if yes, I need to go to the file itself and highlight this word by yello color?

I know how to read the text and find if it contains this word, but how can I go back to the file and highlight it, if possible? thanks

**Comment by gen2brain** [comment]
Hi, there are no plans to add such features, this was planned to be just a simple wrapper for mupdf, not fully featured bindings.
