### ISSUE TITLE
error: cannot recognize xref format

### ISSUE THREAD

**Issue by go-package-lab** [gen2brain/go-fitz#36]
Pdf can be converted into pictures normally, but there will be err error message. It is unclear how to close it?

error: cannot recognize xref format
warning: trying to repair broken xref
warning: repairing PDF document

**Comment by wmattei** [comment]
Any update on this issue? Can't find the reason why i keep getting this warnings..

**Comment by gen2brain** [comment]
Fixed in https://github.com/gen2brain/go-fitz/issues/55.
