### ISSUE TITLE
 cannot find builtin CJK font

### ISSUE THREAD

**Issue by chrions** [gen2brain/go-fitz#37]
error: cannot find builtin CJK font

How do I solve it !!!

**Comment by gen2brain** [comment]
Use the external library instead of internally built purposely without cjk.

**Comment by gen2brain** [comment]
@helios741 As written above and in README, bundled libraries are built without CJK, use the external library if you need them. With CJK libraries would be 10x larger, binary would be about 50M and I don't use it or need it.

**Comment by helios741** [comment]
@gen2brain Thank you so much. i'v resolved this issue by building  external library.
