### ISSUE TITLE
# github.com/gen2brain/go-fitz    |      /go/pkg/mod/github.com/gen2brain/go-fitz@v1.18.0/fitz.go:8:10: fatal error: mupdf/fitz.h: No such file or directory

### ISSUE THREAD

**Issue by andysteve** [gen2brain/go-fitz#41]
Am new to golang, and I need to generate a thumbnail from pdf when I upload it. am using go-fitz library with docker and golang.

But am getting challenged on building docker image including ImageMagick

Docker set up
______________________________________________________________
FROM golang:alpine AS build
RUN apk --no-cache add gcc g++ make git 

WORKDIR /go/src/app

COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .

RUN GOOS=linux go build -tags extlib -ldflags="-s -w" -o ./bin/web-app ./main.go

FROM alpine:3.13
RUN apk --no-cache add ca-certificates
WORKDIR /usr/bin
COPY --from=build /go/src/app/bin /go/bin
EXPOSE 2053
ENTRYPOINT /go/bin/web-app --port 2053

------------------------------------------------------

![image](https://user-images.githubusercontent.com/12824973/147837364-8cf5c841-f302-4b31-af18-e118081f35db.png)

# github.com/gen2brain/go-fitz
/go/pkg/mod/github.com/gen2brain/go-fitz@v1.18.0/fitz.go:8:10: fatal error: mupdf/fitz.h: No such file or directory
    8 | #include <mupdf/fitz.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.

---------------------
Thanks

**Comment by gen2brain** [comment]
You are using `extlib` tag and you don't install the external library. See https://github.com/gen2brain/go-fitz/issues/35.
