### ISSUE TITLE
Checksum mismatch error on go get

### ISSUE THREAD

**Issue by matheuscandido** [gen2brain/go-fitz#42]
Hello, I'm currently getting the following error on `go get` this package:
```
verifying github.com/gen2brain/go-fitz@v1.18.0: checksum mismatch
	downloaded: h1:2fa6dEQmSv1utU4Zb8NaY8bjzhfATyiKrs4nffGel7M=
	go.sum:     h1:vZQRGgQZqHzZRGRnvSUDwz26YD0ZnIyprAvR2C+Hh24=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```
My go version is `go version go1.16.13 linux/amd64`. There seems to be some tagging error of some sorts.

**Comment by gen2brain** [comment]
That is probably because of the force tag, so remove the earlier downloaded.

**Comment by prabhuomkar** [comment]
> so remove the earlier downloaded.
Can you explain what do you mean by earlier downloaded and how to remove it?

**Comment by gen2brain** [comment]
@prabhuomkar remove it from $GOPATH/pkg/mod or with go clean -modcache (https://go.dev/ref/mod#module-cache)

**Comment by thynquest** [comment]
Hello there
I have the same error .. even after trying what @gen2brain mentionned about removing from `$GOPATH/pkg/mod` I have the same error.. any updates on this ? 
thank you for your help

**Comment by gen2brain** [comment]
@thynquest There will be no updates on this. The new release is up.
