### ISSUE TITLE
aborting at reloc.c line 443 in bfd_get_reloc_size

### ISSUE THREAD

**Issue by loganv** [gen2brain/go-fitz#43]
# github.com/gen2brain/go-fitz
/usr/bin/ld: BFD version 2.20.51.0.2-5.44.el6 20100205 internal error, aborting at reloc.c line 443 in bfd_get_reloc_size
/usr/bin/ld: Please report this bug.

这是我的系统信息
Linux version 2.6.32-754.35.1.el6.x86_64 (mockbuild@x86-02.bsys.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-23) (GCC) ) #1 SMP Sat Nov 7 12:42:14 UTC 2020

**Comment by gen2brain** [comment]
You are using a very old GCC compiler on a distro that is not supported anymore. Compile on a newer distro and copy binary if you must use it.
