### ISSUE TITLE
Bazel can't find the mupdf lib

### ISSUE THREAD

**Issue by LuizEduardoCardozo** [gen2brain/go-fitz#46]
Hello!

I'm trying to create a bazel pipeline in a project that uses the go-fitz, but I'm getting the following error:

```
INFO: Build option --define has changed, discarding analysis cache.
INFO: Analyzed 2 targets (0 packages loaded, 7401 targets configured).
INFO: Found 2 targets...
ERROR: /home/eduardo.cardozo/.cache/bazel/_bazel_eduardo.cardozo/298e3f4ef742d30c2aa0ed162984106b/external/com_github_gen2brain_go_fitz/BUILD.bazel:3:11: GoCompilePkg external/com_github_gen2brain_go_fitz/go-fitz.a failed: (Exit 1): builder failed: error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -tags extlib,pkgconfig,extlib,pkgconfig -src ... (remaining 29 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox
/usr/bin/ld.gold: error: cannot find -lmupdf_linux_amd64
/usr/bin/ld.gold: error: cannot find -lmupdfthird_linux_amd64
/tmp/rules_go_work-002962491/_cgo_main.o:_cgo_main.c:_cgohack_fz_default_color_params: error: undefined reference to 'fz_default_color_params'
/tmp/rules_go_work-002962491/_cgo_main.o:_cgo_main.c:_cgohack_fz_identity: error: undefined reference to 'fz_identity'
...
```

Basically, it looks like the libmupdf wasn't being found by the linker gold, which bazel uses to link their built binaries.

Link for and example project:
https://github.com/LuizEduardoCardozo/bazel-go-fitz

You can reproduce it by running the following command

```
bazel build ...
```

Does anyone knows how can I fix this?

**Comment by gen2brain** [comment]
You are building with `-tags extlib,pkgconfig,extlib,pkgconfig`, so it expects you to install mupdf libraries and all dependencies and will not use bundled static libraries.

**Comment by gen2brain** [comment]
But then again, it wants mupdf_linux_amd64, which is a static library bundled, it would need only `-lmudpf` in that case. No idea, can you build with go build? Does bazel uses `go build` or some of their implementation?

**Comment by LuizEduardoCardozo** [comment]
The `tags` was a test that I did before. I updated the error file to the version without it, and the error is the same...

The project builds normally with `go build`, the problem only occurs with `bazel build`.

And I think yes, the bazel just wraps the go compiler. I'm looking in the go_rules repository to check for some "default tags" that could be the cause.

The "-lmupdf" is being used, but it's in go-fitz BUILD.bazel. This error is caused by it: I tell to bazel use the mupdf lib, but it's doesn't find it.

**Comment by gen2brain** [comment]
No idea, as you can see from the previous bazel issue it seemed like it does not respect build tags at all, it enabled them all by default and that is not how it should work.

Anyway, nothing that I can fix here, this library is specific in that it includes static libraries, so vendoring will not work then (it will not copy libraries), etc. unless you use your external libraries and `extlib` tag.

**Comment by wisechengyi** [comment]
To follow up, or we found a way to build it in bazel, here is a manual diff on top of what can be generated automatically by gazelle, which essentially does two things
1. include the header files directly into `go_library`
2. put .a files into a cc_library target and add to the `go_library` as `cdeps`, inspired by https://github.com/bazelbuild/bazel-gazelle/issues/1120#issuecomment-1011081459

```
diff --git a/BUILD.bazel b/BUILD.bazel
index e8ba74f..2dc361d 100755
--- a/BUILD.bazel
+++ b/BUILD.bazel
 
+cc_library(
+    name = "clib",
+    srcs = select({
+        "@io_bazel_rules_go//go/platform:darwin_amd64": [
+            "libs/libmupdf_darwin_amd64.a",
+            "libs/libmupdfthird_darwin_amd64.a",
+        ],
+        "@io_bazel_rules_go//go/platform:darwin_arm64": [
+            "libs/libmupdf_darwin_arm64.a",
+            "libs/libmupdfthird_darwin_arm64.a",
+        ],
+        "@io_bazel_rules_go//go/platform:linux_amd64": [
+            "libs/libmupdf_linux_amd64.a",
+            "libs/libmupdfthird_linux_amd64.a",
+        ],
+        "@io_bazel_rules_go//go/platform:linux_arm64": [
+            "libs/libmupdf_linux_arm64.a",
+            "libs/libmupdfthird_linux_arm64.a",
+        ],
+        "//conditions:default": ["UNSUPPORTED_PLATFORM"],
+    }),
+)
+
 go_library(
     name = "fitz",
     srcs = [
         "fitz.go",
         "fitz_cgo.go",
         "fitz_content_types.go",
-    ],
+    ] + glob(["include/**/*.h"]),
+    cdeps = [":clib"],
     cgo = True,
```
