### ISSUE TITLE
vendor/github.com/gen2brain/go-fitz/fitz.go:9:10: fatal error: 'mupdf/fitz.h' file not found

### ISSUE THREAD

**Issue by thynquest** [gen2brain/go-fitz#48]
Hello there

May be this case was already treated but I can't find a way around this. I am trying to compile a basic example using this library but nothing seems to work. this is the command I use

`go build -tags "extlib"  -o bin/sample main.go`.

Of course I installed mupdf first using homebrew (I am on macos) but the build does not work. I also tried to add env variable such as `LIBRARY_PATH` or `LDFLAGS` but with no result. the basic example I am trying to compile is the one on the project page. Based on what I have understood the could be a way to build just by using the bundled library.. 
any leads that can point me to the right direction ? 
thanks for the help.

**Comment by gen2brain** [comment]
Seems you are trying to use both vendor and extlib? Remove vendor, it will not copy all necessary files. If you want to pass additional LDFLAGS/CFLAGS that is done by using CGO_CFLAGS and CGO_LDFLAGS. You can search issues to see how it is done in Dockefile if you want to use an external library.

**Comment by gen2brain** [comment]
Right, so brew installs only static libraries, this is from Catalina VM but probably the same on your OS.

```
% brew ls --verbose mupdf | grep lib
/usr/local/Cellar/mupdf/1.19.1/lib/libmupdf.a
/usr/local/Cellar/mupdf/1.19.1/lib/libmupdf-third.a

% ls -1
example.go
go.mod
go.sum
test.pdf

% go build -o example-embed

% go build -tags 'extlib static' -o example

% otool -L example-embed 
example-embed:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)

% otool -L example
example:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)

% ./example
```
