### ISSUE TITLE
Unable to build deployment package - go-fitz build constraints

### ISSUE THREAD

**Issue by anandsoni11** [gen2brain/go-fitz#49]
In one of my projects, we are using go-fitz (v1.18.0) for pdf generation. However, recently the build package generation fails when we run the below command -
`GOOS=linux GOARCH=amd64 go build -o main`

The error that I get is -
`go build github.com/gen2brain/go-fitz: build constraints exclude all Go files in /<path>/gen2brain/go-fitz@v1.18.0`

This used to work before. Has something changed recently in the past few months?

Raising issue here as I couldnt find a solution to this. Please take a look.

**Comment by gen2brain** [comment]
Are you trying to cross-compile? If yes, you need to set CGO_ENABLED=1, when you change GOARCH or GOOS GO will by default disable cgo, you must enable it.

**Comment by anandsoni11** [comment]
Compiling on Mac, target OS is linux. Just setting CGO_ENABLED=1 doesnt work. Do I need a C cross-compiler as well? How to do that? Error after setting CGO_ENABLED=1 -
`# runtime/cgo
linux_syscall.c:67:13: error: implicit declaration of function 'setresgid' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
linux_syscall.c:67:13: note: did you mean 'setregid'?
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:593:6: note: 'setregid' declared here
linux_syscall.c:73:13: error: implicit declaration of function 'setresuid' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
linux_syscall.c:73:13: note: did you mean 'setreuid'?
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:595:6: note: 'setreuid' declared here`

**Comment by gen2brain** [comment]
Sure, of course, you need a cross-compiler. You can try with `CC="clang --target=x86_64-unknown-linux-gnu"`, or you can try with `zig`, something like `CC="zig cc -target x86_64-linux-gnu"`.

**Comment by anandsoni11** [comment]
Using zig, it compiles but gives a segmentation fault during runtime.

**Comment by gen2brain** [comment]
You can try with docker, etc. Not an issue here but a user issue. Closing.
