### ISSUE TITLE
Go-fitz is incompatible with go-iup

### ISSUE THREAD

**Issue by rasteric** [gen2brain/go-fitz#53]
Finally, I figured out the problem I initially had with go-iup! If go-fitz is imported, too, then running the executable results in the dreaded Pango error:

`Pango-ERROR **: 17:38:29.868: Harfbuzz version too old (1.3.2) `

or a segmentation violation. Since you're the maintainer of both packages, it might be worth looking at a way to fix this problem.

To repeat the problem:
```
package main

import (
	"github.com/gen2brain/iup-go/iup"
    // _ "github.com/gen2brain/go-fitz"
)

func main() {
	iup.Open()
	defer iup.Close()


	lbl := iup.Label("This is a test label.")

	dlg := iup.Dialog(
		lbl,
		)
	dlg.SetAttribute("TITLE", "Label")

	iup.Show(dlg)
	iup.MainLoop()
}
```
It works. Uncomment the line importing go-fitz, and the recompiled executable crashes. (My executable shows the Pango error instead of crashing when go-fitz is imported but I wasn't able to repeat that in the minimal example.) I'm putting the issue here although I can't say which package is the real culprit. In any case, they seem to require incompatible Pango versions.

Tested on Linux Mint 20.3, which is based on Ubuntu 20.04.

**Comment by gen2brain** [comment]
It now also works with embedded libraries, changed in https://github.com/gen2brain/go-fitz/commit/70eeb5e5ecc4b920b9a82ed09c10edca1b3a5c72 as suggested here https://stackoverflow.com/questions/40275687/gtk3-c-program-linked-with-mupdf-fails-even-if-not-called/51389531#51389531
