### ISSUE TITLE
Detect corrupt/broken files

### ISSUE THREAD

**Issue by gen2brain** [gen2brain/go-fitz#57]
MuPDF uses a `setjmp` based exception handling system, i.e fz_try/fz_always/fz_catch. In order to detect if file is broken or not this needs to be somehow implemented in Go.

**Comment by nouritsu** [comment]
Any plans on fixing this?

**Comment by gen2brain** [comment]
Do you have any idea how this can be fixed?

**Comment by nouritsu** [comment]
A quick and dirty fix I have thought of is as follows -
```go
_, _, err := pdf.Open(fpath)
if err != nil {
/*Handle error*/
}
```
I don't think it'll be much slower since pdf.Open returns an error as soon as it detects a corrupt xref.
If it being slower is a concern, I'd love to see an alternative function provided to check pdf integrity.

**Comment by gen2brain** [comment]
It is not a concern that it will be slower, but just that will not work. `C.fz_open_document(f.ctx, cfilename)` from MuPDF will just crash with a corrupt/invalid file, it expects one to "catch" exception based on `setjmp` in C.

**Comment by nouritsu** [comment]
it seems to work for me. I use it as follows -
```go
func (p Parser) PDF(fpath string) (string, error) {
	var sb strings.Builder

	_, _, err := pdf.Open(fpath)
	if err != nil {
		return "", err
	}

	doc, err := fitz.New(fpath)
	if err != nil {
		return "", err
	}
	defer doc.Close()
       /*Rest of the parser*/
}
```
I simply use the pdf.Open() function in go to check if the file is corrupted or not. It would be great if the fitz.New() function could return an error if pdf.Open() returns an error.

**Comment by gen2brain** [comment]
Where does `pdf.Open()` comes from, is that some different library?

**Comment by nouritsu** [comment]
Its another library @ github.com/ledongthuc/pdf
I suggest borrowing their method of error checking.

**Comment by gen2brain** [comment]
That would mean basically the whole read file here https://github.com/ledongthuc/pdf/blob/master/read.go.

**Comment by gen2brain** [comment]
Thanks, that can be a way for users to avoid this problem, but I am not going to add 1K lines to check for corrupted files. I would prefer some solution with `setjmp` or whatever that can check that straight from MuPDF.

**Comment by nouritsu** [comment]
Fair enough, could you please add this to the readme.md file?
I'm sure there are many users who want this fix.

**Comment by gen2brain** [comment]
For now, let it be just here in the issue. I guess I can try to create a wrapper for Open() in C, with fz_try/fz_catch, and then use that instead of `C.fz_open_document/C.fz_open_memory`. If I fail I can add your info to the readme. Not sure when will I find time though, but soon.

**Comment by hudon** [comment]
as far as I can tell, the only way to deal with this is to wrap the whole API with an "exception-less" one, which does `fz_catch` and converts and "exceptions" to error values, and the consume this wrapper in Go. :/

**Comment by hudon** [comment]
Further reading... https://artifex.com/blog/an-improved-mupdf-api-using-c-plus-plus
Looks like they may have a C++ API which converts these "exceptions" to C++ exceptions, and then they use this API and SWIG to help generate the Python bindings... could be worth looking into if SWIG can help you generate Go bindings.

**Comment by gen2brain** [comment]
This should be fixed in https://github.com/gen2brain/go-fitz/commit/f15918d712b55047e829b1fe6ce0b46651ca0e40.
