### ISSUE TITLE
Suggested fix for `recompile with -fPIC` does not work

### ISSUE THREAD

**Issue by postables** [gen2brain/go-fitz#6]
Following the suggestions in the readme, downloading the package with `go get -u github.com/gen2brain/go-fitz` gives me the `-fPIC` issue seen here https://gist.github.com/postables/4b603bb0e82ac4203b35dc49a50622e2

downloading the package with `go get -u -tags gcc7 github.com/gen2brain/go-fitz` doesn't give me any errors, however running `go vet ./...` produces the error seen here https://gist.github.com/postables/9eca025ea57f79d22c64acd945bee2fe the same issue is produced with `go build` and `go test`

`uname -a`:
```
Linux dark 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

`/etc/lsb-release`:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Pop!_OS 18.04 LTS"
```

`go version`:
```
go version go1.11.1 linux/amd64
```

I have replicated the issue on a separate machine with the following specs:

`uname -a`:
```
Linux ipfs-node-1 4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

`/etc/lsb-release`:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
```

`go version`:
```
go version go1.10.3 linux/amd64
```

Update:

It appears that running with `go vet -tags gcc7 ./...` solves the issue. However, I'm unclear as to how one can get around this issue while using this library on systems which require this work-around

**Comment by postables** [comment]
Was able to fix all my issues by using `-tags gcc7` everywhere.

**Comment by gen2brain** [comment]
From gcc version 7 `--enable-default-pie` option is enabled by default, so that creates issues with static libraries during linking.
Probably that should be default, and then tag can be renamed to `nopie`  and should be used on old distros with old gcc.
