### ISSUE TITLE
fatal error: mupdf/fitz.h: No such file or directory

### ISSUE THREAD

**Issue by lsjhtang** [gen2brain/go-fitz#60]
go version go1.17.5 linux/amd64

go mod vendor
go run main.go

# github.com/gen2brain/go-fitz
../../vendor/github.com/gen2brain/go-fitz/fitz.go:6:24: fatal error: mupdf/fitz.h: No such file or directory
 #include <mupdf/fitz.h>

**Comment by gen2brain** [comment]
Do not use vendoring, it will copy only .go files.
