### ISSUE TITLE
pdf convert to image ,oom

### ISSUE THREAD

**Issue by PycMono** [gen2brain/go-fitz#66]
hello，
here is my issue，
when pdf convert to image
The pod Out Of Memory ，oomkilled。
// ImageDPI returns image for given page number and DPI.
func (f *Document) ImageDPI(pageNumber int, dpi float64) (image.Image, error) {
   // ....
   img.Pix = C.GoBytes(tt, C.int(4*bbox.x1*bbox.y1))
   // ....
}
![profile004](https://user-images.githubusercontent.com/16773867/200384722-cb423cbd-41a9-40f7-b940-58932f1aad98.svg)

**Comment by gen2brain** [comment]
This needs more information, how much memory you have, how large the file etc. PDF parsing usually takes a lot of memory. Sorry, I don't have time to support your issue. You can reopen it if you have more information, thanks.
