### ISSUE TITLE
How to across-compile from mac to linux

### ISSUE THREAD

**Issue by czh0318** [gen2brain/go-fitz#7]
Hi:
    My os is macOs, now i need to compile binary to run on centos7, i use the command GOOS=linux GOARCH=amd64 go build, and there is an error:
go build github.com/gen2brain/go-fitz: build constraints exclude all Go files in /Users/allen/works/go/src/github.com/gen2brain/go-fitz.

  Look forward to your reply.

**Comment by gen2brain** [comment]
Hello,

You cannot just cross compile with simple GOOS=linux GOARCH=amd64 go build for example, library uses https://golang.org/cmd/cgo/, so you need to have compiler and toolchain for arch you want to build for. Also, enable CGO_ENABLED=1.
For example I have on my Linux system mingw toolchain in /usr/x86_64-w64-mingw32 and x86_64-w64-mingw32-gcc in PATH, so I can just CC=x86_64-w64-mingw32-gcc GOOS=windows GOARCH=amd64 go build to cross compile for Windows.

Not sure how you can do that on macOS. Library uses precompiled mupdf libraries, but they still need to be linked at the end with the appropriate toolchain.

**Comment by czh0318** [comment]
Thank you very much. I will try it

**Comment by ivanmartos** [comment]
@czh0318 how did you pls manage to fix it?

**Comment by asish-tom-fin** [comment]
> Thank you very much. I will try it
@czh0318 czh0318
Hi, are you able to cross-compile it in mac?

**Comment by gen2brain** [comment]
I used https://github.com/tpoechtrager/osxcross in Linux to build macOS binary, not exactly for this project, but it should be the same. I know I saw Linux binary toolchain for MacOS on github recently, but with a quick search, I didn't found it.

**Comment by gen2brain** [comment]
@ivanmartos @asish-tom-fin See https://stackoverflow.com/questions/5245444/cross-compiler-for-linux-on-mac-os-x/14145566 and https://blog.filippo.io/easy-windows-and-linux-cross-compilers-for-macos/.
