### ISSUE TITLE
Go build error: undefined: fitz.New

### ISSUE THREAD

**Issue by JensvandeWiel** [gen2brain/go-fitz#74]
Does not matter what i use: NewFromReader, NewFromMemory or New it throws the same error

**Comment by JensvandeWiel** [comment]
i've tried everything but i can not get it to work. ill try to reproduce it on another machine

**Comment by JensvandeWiel** [comment]
its something in the enviroment

**Comment by JensvandeWiel** [comment]
dont know what yet

**Comment by ivanmartos** [comment]
I'm having same issue
go mod
```

go 1.20

require (
	github.com/gen2brain/go-fitz v1.20.2
)
```

I'm receiving compile time errors
```
internal/dataMatrixParser/services.go:16:58: undefined: fitz.Document
```


Code snippet
```
package XXX

import (
"bytes"
"github.com/gen2brain/go-fitz"
"github.com/XXX/XXXXX/internal/model"
"image"
)

type MatrixParser interface {
	ParsePdf(parsingRequest model.ParsingRequest, doc *fitz.Document) (*bytes.Buffer, error)
}
}
```
```

**Comment by 15365917109** [comment]
我也遇到同意的问题 请问你解决了吗

**Comment by gen2brain** [comment]
I guess you all are using Windows. The most simple way to install the GCC compiler for me on Windows was to use TDM-GCC. There is also mingw64, you need to install the compiler for the arch you are going to use. I guess if anyone just enabled verbose build everything should be clear. Anyway, this is not the right place for such questions.

**Comment by dyhgoa** [comment]
Error undefined: fitz.NewFromMemory  : Fitz in cross compiling Linux under Windows 10

**Comment by gen2brain** [comment]
@dyhgoa When you cross-compile, Go will set CGO_ENABLED to 0, when you set it to 1, you will see the real error message, i.e. you want to compile for Linux with C compiler for Windows, etc. Of course, you cannot just change GOOS and expect it to work.
