### ISSUE TITLE
Error: ./PDFToImg.go:21:19: undefined: fitz.New

### ISSUE THREAD

**Issue by JensvandeWiel** [gen2brain/go-fitz#76]
https://github.com/gen2brain/go-fitz/issues/74

still get Error: ./PDFToImg.go:21:19: undefined: fitz.New

now i'm trying it in a github workflow and still get the error when trying to build for windows.

https://github.com/JensvandeWiel/schoolantwoorden-cli/actions/runs/4637349791/jobs/8206156685

code:
https://github.com/JensvandeWiel/schoolantwoorden-cli/blob/master/PDFToImg.go

**Comment by ivanmartos** [comment]
I'm facing same issues
https://github.com/gen2brain/go-fitz/issues/74#issuecomment-1509872340

**Comment by DerRueter** [comment]
I had the same problems, try installing the c and c++ compilers. At least that worked for me.
I've analysed it via sysinternals with procmon and saw that go.exe was looking for gcc.

Guide:
https://www.freecodecamp.org/news/how-to-install-c-and-cpp-compiler-on-windows/

**Comment by gen2brain** [comment]
Sorry, I don't have time to work on the user issues. The basic CGO setup is what is needed here, and this is not the place to ask for help for that. If there is actually something wrong with the go-fitz repo fill free to reopen the issue, thanks.
