### ISSUE TITLE
error: cannot find builtin CJK font

### ISSUE THREAD

**Issue by Insua** [gen2brain/go-fitz#77]
some invoice pdf convert show this error

**Comment by gen2brain** [comment]
CJK fonts are not included in precompiled libraries, you must use external mupdf library.

**Comment by Insua** [comment]
``
➜  pdf2image git:(master) go build -tags=extlib
# github.com/gen2brain/go-fitz
/home/insua/go/pkg/mod/github.com/gen2brain/go-fitz@v1.20.2/fitz.go:6:10: fatal error: mupdf/fitz.h: No such file or directory
    6 | #include <mupdf/fitz.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
``

use external show errors

**Comment by gen2brain** [comment]
@Insua see https://github.com/gen2brain/go-fitz/issues/35#issuecomment-1434655187
