### ISSUE TITLE
Docker golang:alpine "cannot find -lmupdf_linux_arm64_musl: No such file or directory"

### ISSUE THREAD

**Issue by normangoh** [gen2brain/go-fitz#79]
Hi @gen2brain,

May I have your advises on what might be wrong? I received the following error when I am doing as advised.

<img width="890" alt="Screenshot 2023-04-23 at 9 49 12 PM" src="https://user-images.githubusercontent.com/48743313/233843713-099b79a0-2644-4144-880e-d0be64ccfebf.png">
<img width="1434" alt="Screenshot 2023-04-23 at 9 43 13 PM" src="https://user-images.githubusercontent.com/48743313/233843723-8bbfb963-6b05-42c3-9a31-a123e9550aa9.png">

**Comment by gen2brain** [comment]
The libraries are updated to the latest version, this issue should be fixed now. Please check with v1.22.0.
