### ISSUE TITLE
go mod vendor local vendor dir not include libs dir and include dir

### ISSUE THREAD

**Issue by andotorg** [gen2brain/go-fitz#80]
![image](https://user-images.githubusercontent.com/25116294/234450036-c0a5031b-6980-4d24-a9d1-a25a1de0d4d6.png)
Missing cgo dependency package directory

**Comment by andotorg** [comment]
After manually adding this directory, running go mod vendor will also result in loss

**Comment by gen2brain** [comment]
@andotorg Do not use vendor, as you noticed it will not copy all files.

**Comment by akaswenwilk** [comment]
do you have any suggestions then on how to debug with delve in packages?  This doesn't work without go mod vendor.

**Comment by gen2brain** [comment]
@*akaswenwilk* The issue is a few years old. Support for the vendor was
added. Did you try it, or did you just go straight to the issues?
