### ISSUE TITLE
error: cannot find builtin CJK font

### ISSUE THREAD

**Issue by Garfield-yin** [gen2brain/go-fitz#83]
doc.ImageDPI error:doc.ImageDPI
version: github.com/gen2brain/go-fitz v1.22.2
go version:GO_VERSION=1.18.3 
system: ubuntu:16.04

**Comment by gen2brain** [comment]
CJK fonts are not included ind bundled libraries, use external library.

**Comment by Garfield-yin** [comment]
Thank you for your prompt response and for providing clarification on this matter. I understand now that CJK fonts are not included in the bundled libraries, and that it's recommended to use an external library instead.

As I am not familiar with this process, could you possibly provide some guidance or documentation on how to incorporate an external library for CJK fonts? Any example of usage or step-by-step instructions would be greatly appreciated.

Thank you in advance for your time and help. I look forward to your response.
