### ISSUE TITLE
outline.page.page undefined (type _Ctype_int has no field or method page) compiler (MissingFieldOrMethod)

### ISSUE THREAD

**Issue by bhambrah-asbuilt** [gen2brain/go-fitz#84]
getting error in this line: https://github.com/gen2brain/go-fitz/blob/master/fitz.go#L499
**outline.page.page undefined (type _Ctype_int has no field or method page) compiler (MissingFieldOrMethod)**

using github.com/gen2brain/go-fitz v1.22.2
on Ubuntu 22.04.2 LTS
go version go1.19.3 linux/amd64

**Comment by gen2brain** [comment]
It is not clear, are you trying to use an external library? If that is the case either install the latest mupdf version or use the older version of `go-fitz`.

**Comment by bhambrah-asbuilt** [comment]
> It is not clear, are you trying to use an external library? If that is the case either install the latest mupdf version or use the older version of `go-fitz`.

@gen2brain i am trying to use `go-fitz` to convert a pdf to png.
however, after installing it using `go get` command and using it in my code, i run into this error.

**Comment by gen2brain** [comment]
Sure, and `go-fitz` is a wrapper for MuPDF, it comes with bundled library without CJK fonts or the user can use the full external library via tags. So, it is important to know how are you "trying to use" the library. As you can see it is tested and is working on Ubuntu, macOS, and Linux and it works. It looks like an API change in MuPDF that happened around version 1.14, so you are using an external library and some old external version?

**Comment by bhambrah-asbuilt** [comment]
> Sure, and `go-fitz` is a wrapper for MuPDF, it comes with bundled library without CJK fonts or the user can use the full external library via tags. So, it is important to know how are you "trying to use" the library. As you can see it is tested and is working on Ubuntu, macOS, and Windows and it works. It looks like an API change in MuPDF that happened around version 1.14, so you are using an external library and some old external version?

@gen2brain sorry for my lack of knowledge here. I understand it is tested and works on different platforms; just that i haven't been able to use it in my code.
are there any prerequisites to be able to use it?
i have already installed latest version of mupdf using `apt-get`
and then i am installing `go-fitz` (`go get github.com/gen2brain/go-fitz`), running mod vendor and using in my code.

closing the issue, but any help will be appreciated.

**Comment by gen2brain** [comment]
What is the version of mupdf you are using? Do you have a need to use external library at all?
