### ISSUE TITLE
doc.HTML() can it support <table> <tr> <td>?

### ISSUE THREAD

**Issue by DaFlyX** [gen2brain/go-fitz#89]
doc.HTML() now returns p tags including span tags. If pdf contains tables, can it support table> tr> td?

**Comment by DaFlyX** [comment]
doc.HTML() now returns p > span tags,
If the pdf contains table>tr>td, can it be supported
What about this return?

**Comment by gen2brain** [comment]
No idea, these are bindings for MuPDF. Did you test it? If so, you can reply with the comment so other people will know.
