### ISSUE TITLE
Memory leak when rendering pages

### ISSUE THREAD

**Issue by octacian** [gen2brain/go-fitz#9]
The following code is modified from the README, simplified to the greatest extent possible.
```go
package main

import "github.com/gen2brain/go-fitz"

func main() {
	doc, err := fitz.New("test.pdf")
	if err != nil {
		panic(err)
	}

	defer doc.Close()

	// Extract pages as images
	for n := 0; n < doc.NumPage(); n++ {
		_, err := doc.Image(n) // <- Memory leak here
		if err != nil {
			panic(err)
		}
	}
}
```

The above code produced a memory leak at the call to `doc.Image`. When executed on a longer PDF where rendering each slide results in an image ranging from 1 to 5 MB (averaging 1.9 MB in size), the program easily uses an entire gigabyte of RAM before 30 seconds has passed.

A similar pattern can be observed when calling `doc.SVG` and `doc.HTML`, although both are generally speaking lighter on the RAM usage. I haven't observed this leak when calling `doc.Text`, but this may just as well be because the operation occurs much faster due to its simplicity.

**Comment by gen2brain** [comment]
That doesn't mean necessarily that there is a memory leak. MuPDF tries hard to maintain stuff in memory as much as possible for performance reasons so any font or image is held in memory. `mutool` for example have the option to limit memory, also `imagemagick` when working with PDF can consume a LOT of memory, and recommends `-limit memory`.

I now added FZ_NO_CACHE for all devices, so it doesn't try to cache everything. You can test if there are any differences, I don't see anything obviously wrong currenty that needs to be closed/freed.

**Comment by octacian** [comment]
With your changes, RAM usage does not increase nearly as fast, but by the end of a 132 page PDF, it still managed to get up to 1.8 GiB at times. It does seem to have improved, and if there are any issues it sounds as though they would be in the upstream library. So this issue could probably be closed.

However, I do question why so much RAM usage is necessary at all. I don't know much about how PDFs work, but I'm pretty sure that browsing the internet requires rendering far more complex information than would be found in an average PDF file, and while browsers do tend to use a fairly substantial amount, I have yet to see one eat up RAM quite like this.
