### ISSUE TITLE
linux compilation error

### ISSUE THREAD

**Issue by zzdboy** [gen2brain/go-fitz#90]
github.com/gen2brain/go-fitz@v1.22.2/libs/libmupdfthird_linux_amd64.a(one.o): relocation R_X86_64_PC32 against symbol `stdout@@GLIBC_2.2.5' can not be used when making a PDE object; recompile with -fPIE\n/usr/bin/ld: final link failed: bad value\ncollect2: error: ld returned 1 exit status\n\n

@gen2brain

**Comment by gen2brain** [comment]
https://github.com/gen2brain/go-fitz/issues/85

**Comment by zzdboy** [comment]
Ok, thank you for your reply

**Comment by gen2brain** [comment]
@zzdboy You can compile binary on recent OS and then use that binary on old OS. Sorry, but as mentioned in other issue I don't have time to support old systems. Alternative is also to use external library.
