### ISSUE TITLE
fitz is empty

### ISSUE THREAD

**Issue by Deme94** [gen2brain/go-fitz#94]
Hey, fitz hasn't any methods. I imported it but I can't use any of its functions.

fitz.New is not compiling, what should I do?

**Comment by gen2brain** [comment]
You probably have CGO_ENABLED=0, you need to enable CGO. I am just guessing.

**Comment by Deme94** [comment]
> You probably have CGO_ENABLED=0, you need to enable CGO. I am just guessing.

Yeah and I also didn't have gcc installed (I installed ubuntu a few days ago).
Thank you very much for the quick answer, you just saved my day and my job.

Best regards and thank you
